name: docker-image
on:
  push:
    branches: [ "main" ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    if: github.repository == 'ddmms/ml-peg'
    permissions:
      packages: write
      contents: read
    steps:
      - name: "Login to ghcr"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./containers/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ddmms/ml-peg-app:amd64-latest
            ghcr.io/ddmms/ml-peg-app:amd64-${{ github.sha }}

  build-arm64:
    runs-on: ubuntu-24.04-arm
    if: github.repository == 'ddmms/ml-peg'
    permissions:
      packages: write
      contents: read
    steps:
      - name: "Login to ghcr"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: ./containers/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/ddmms/ml-peg-app:arm64-latest
            ghcr.io/ddmms/ml-peg-app:arm64-${{ github.sha }}
